#!/usr/bin/env bash 
clear

echo "Informacoes muito importantes!"
echo "-----------------------------------------------"
echo -n "Usuario: "
whoami 

echo -n "Hostname: "
hostname

echo -n "Uptime: "
uptime -p

echo -n "Kernel: "
uname -rms

echo ""

echo "-----------------------------------------------"